### ISSUE TITLE
Qdr CRD validation error using kubectl

### ISSUE THREAD

**Issue by fgiorgetti** [interconnectedcloud/qdr-operator#12]
When following instructions from README to create the Qdr CRD, we are getting a schema validation error with ("cpu" and "memory" fields). It works fine with the "oc" client by the way.

kubectl create -f deploy/crds/interconnectedcloud_v1alpha1_qdr_crd.yaml
error: error validating "deploy/crds/interconnectedcloud_v1alpha1_qdr_crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.deploymentPlan.properties.resources.properties.limits): unknown field "cpu" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.deploymentPlan.properties.resources.properties.limits): unknown field "memory" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.deploymentPlan.properties.resources.properties.requests): unknown field "cpu" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.deploymentPlan.properties.resources.properties.requests): unknown field "memory" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps]; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by ChugR** [comment]
Fixed at commit a219e365
