### ISSUE TITLE
Need ability to set custom annotations on created pods

### ISSUE THREAD

**Issue by ErnieAllen** [interconnectedcloud/qdr-operator#24]
In order for prometheus to scape for metrics for each individual router in a cluster, I need the qdr-operator to support defining a custom attribute for the pods it creates. In my case, the attribute would be the same for every pod: prometheus.io/scrape

I can then do a select for pods that have this attribute.

**Comment by ErnieAllen** [comment]
I should note that I need to define multiple custom attributes, not just one.

**Comment by ajssmith** [comment]
Can you provide the custom attributes that you need to define? Wondering if a general purpose annotation facility is needed or if just the annotations prometheus needs will suffice for now. Thanks.

**Comment by ajssmith** [comment]
https://github.com/interconnectedcloud/qdr-operator/pull/25

adds prometheus.io/port and prometheus.io/scrape

**Comment by ErnieAllen** [comment]
I need the following annotations for prometheus:
prometheus.io/scrape: 'true'
prometheus.io/port: '8672'

The port is the http port that is created by the operator.

**Comment by ajssmith** [comment]
https://github.com/interconnectedcloud/qdr-operator/pull/25
