### ISSUE TITLE
GOCACHE=off in go test is failing with go >= 1.12

### ISSUE THREAD

**Issue by fgiorgetti** [interconnectedcloud/qdr-operator#31]
When running go test with GOCACHE=off I am seeing an error:
_"build cache is disabled by GOCACHE=off, but required as of Go 1.12"_

Based on doc, build cache is now required:
https://tip.golang.org/doc/go1.12#gocache

I was able to bypass it by removing GOCACHE=off and by adding "-count=1", like:

go test -count=1

**Comment by Deeptiman** [comment]
@fgiorgetti  You enable the cache by settings of the env. I did in windows in the following way.

1. Go to `C:\Users\YOUR_PC_NAME\AppData\Roaming\go`
2. open `env` file and change the GOCACHE=C:\Users\YOUR_PC_NAME\AppData\Local\go-build

it will reset GOCACHE to default settings.
